##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Sat May  9 22:18:42 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.sd
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX330TFFG1761_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 8
## Time Period: 1250
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[*]} ]
          
#create_clock -period 1.25 [get_ports sys_clk_i]
          
create_clock -period 5 [get_ports clk_ref_p]
          
############## NET - IOSTANDARD ##################


# PadFunction: IO_L6P_T0_15 
set_property VCCAUX_IO DONTCARE [get_ports {init_calib_complete}]
set_property IOSTANDARD LVCMOS18 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN AM39 [get_ports {init_calib_complete}]

# PadFunction: IO_L4N_T0_38 
set_property VCCAUX_IO DONTCARE [get_ports {tg_compare_error}]
set_property IOSTANDARD LVCMOS18 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN A17 [get_ports {tg_compare_error}]

