##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Sat May  9 22:18:42 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1761
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 8
## Time Period: 1250
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L6P_T0_15 
set_property VCCAUX_IO DONTCARE [get_ports {init_calib_complete}]
set_property IOSTANDARD LVCMOS18 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN AM39 [get_ports {init_calib_complete}]

# PadFunction: IO_L4N_T0_38 
set_property VCCAUX_IO DONTCARE [get_ports {tg_compare_error}]
set_property IOSTANDARD LVCMOS18 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN A17 [get_ports {tg_compare_error}]

