//-----------------------------------------------------------------------------
//
// (c) Copyright 2014 Xilinx, Inc. All rights reserved.
//
//                                                                 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// 	PART OF THIS FILE AT ALL TIMES.                                
//-----------------------------------------------------------------------------
//
// File name:    srio_gt_wrapper_v7_2x.v
// Rev:          4.0
// Description:  This module instantiates the transceivers which perform the
//               PMA functions of the Serial RapidIO core.
//               This is targeted for V7 GTH based device.
//-----------------------------------------------------------------------------
///////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 3.4
//  \   \         Application : 7 Series FPGAs Transceivers Wizard
//  /   /         Filename : srio_gt_wrapper_srio_gen2_5g_2x_16b_v7_2x.v
// /___/   /\
// \   \  /  \
//  \___\/\___\
//
//
// Module srio_gt_wrapper_srio_gen2_5g_2x_16b_v7_2x (a Core Top)
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 
///////////////////////////////////////////////////////////////////////////////

//------------------------------------------------------------------------------
//--This is 2x srio_gt_wrapper_srio_gen2_5g_2x_16b_v7_2x module----
//------------------------------------------------------------------------------


`default_nettype wire

`timescale 1ns / 1ps
`define DLY #1

//***************************** Entity Declaration ****************************
(* DowngradeIPIdentifiedWarnings="yes" *)

(* X_CORE_INFO = "srio_gt_wrapper_srio_gen2_5g_2x_16b_v7_2x,gtwizard_v3_4,{protocol_file=srio_gen2_multi_lane}" *)
(* CORE_GENERATION_INFO = "srio_gt_wrapper_srio_gen2_5g_2x_16b_v7_2x,gtwizard_v3_4,{protocol_file=srio_gen2_multi_lane}" *)
module srio_gt_wrapper_srio_gen2_5g_2x_16b_v7_2x
  #(
    parameter TCQ         = 100,
    parameter LINK_WIDTH  = 2
  )
(
    input                       refclk,
    input                       drpclk,

    input                       gt_clk,
    input                       gt_pcs_clk,
    input                       gt_pcs_rst,
    input                       clk_lock,

    input                       srio_rxn0,
    input                       srio_rxp0,
    output                      srio_txn0,
    output                      srio_txp0,

    input                       srio_rxn1,
    input                       srio_rxp1,
    output                      srio_txn1,
    output                      srio_txp1,

    output [LINK_WIDTH*4-1:0]   gtrx_chariscomma,
    output [LINK_WIDTH*4-1:0]   gtrx_disperr,
    output [LINK_WIDTH*4-1:0]   gtrx_notintable,
    input  [LINK_WIDTH-1:0]     gttx_inhibit,
    output [LINK_WIDTH-1:0]     gtrx_chanisaligned,
    output                      gtrx_reset_req,
    output [LINK_WIDTH-1:0]     gtrx_reset_done,
    input                       gtrx_reset,
    input                       gtrx_chanbonden,
    output [LINK_WIDTH*4*8-1:0] gtrx_data,
    output [LINK_WIDTH*4-1:0]   gtrx_charisk,
    input  [LINK_WIDTH*4*8-1:0] gttx_data,
    input  [LINK_WIDTH*4-1:0]   gttx_charisk,

    // list of transceiver debug ports for GTH starts

    //---- Channel - DRP Ports  ------
    input   [LINK_WIDTH*9-1:0]  gt_drpaddr_in, //  [8:0]
    input   [LINK_WIDTH*16-1:0] gt_drpdi_in,    // [15:0]
    output  [LINK_WIDTH*16-1:0] gt_drpdo_out,   // [15:0]
    input   [LINK_WIDTH-1:0]    gt_drpen_in,
    output  [LINK_WIDTH-1:0]    gt_drprdy_out,
    input   [LINK_WIDTH-1:0]    gt_drpwe_in,

    //---- TX Initialization and Reset Ports ------
    input   [LINK_WIDTH-1:0]    gt_txpmareset_in,
    input   [LINK_WIDTH-1:0]    gt_txpcsreset_in,
    output  [LINK_WIDTH-1:0]    gt_txresetdone_out,

    //---- Receive Ports - RX Initialization and Reset Ports -----
    input   [LINK_WIDTH-1:0]    gt_rxpmareset_in,
    input   [LINK_WIDTH-1:0]    gt_rxpcsreset_in,
    output  [LINK_WIDTH-1:0]    gt_rxresetdone_out,

    //---- Transmit/Rececive Ports - TX/Rx Buffer Ports -----
    output  [LINK_WIDTH*2-1:0]  gt_txbufstatus_out,
    output  [LINK_WIDTH*3-1:0]  gt_rxbufstatus_out,

    //---- RX Margin Analysis Ports -----
    input   [LINK_WIDTH-1:0]    gt_eyescantrigger_in,
    input   [LINK_WIDTH-1:0]    gt_eyescanreset_in,
    output  [LINK_WIDTH-1:0]    gt_eyescandataerror_out,

    //---- Loopback Ports -----
    input  [LINK_WIDTH*3-1:0]   gt_loopback_in,

    //---- Receive Ports - RX Polarity Control Ports -----
    input  [LINK_WIDTH-1:0]     gt_rxpolarity_in,

    //---- Transmit Ports - TX Polarity Control Ports -----
    input  [LINK_WIDTH-1:0]     gt_txpolarity_in,

    //---- Receive Ports - RX Equalizer Ports -----
    input  [LINK_WIDTH-1:0]     gt_rxdfelpmreset_in,

    //---- Receive Ports - RX Margin Analysis ports -----
    input  [LINK_WIDTH-1:0]     gt_rxlpmen_in,

    //---- TX Configurable Driver Ports -----
    input   [LINK_WIDTH*5-1:0]  gt_txprecursor_in,
    input   [LINK_WIDTH*5-1:0]  gt_txpostcursor_in,

    //---- Transmit Ports - TX Configurable Driver Ports -----
    input   [3:0]               gt0_txdiffctrl_in,
    input   [3:0]               gt1_txdiffctrl_in,

    //---- Transmit Ports - Pattern Generator Ports -----
    input   [LINK_WIDTH-1:0]    gt_txprbsforceerr_in,

    //---- Transmit Ports - pattern Generator Ports -----
    input   [LINK_WIDTH*3-1:0]  gt_txprbssel_in,

    //---- Receive Ports - Pattern Checker Ports -----
    input   [LINK_WIDTH*3-1:0]  gt_rxprbssel_in,
    output  [LINK_WIDTH-1:0]  gt_rxprbserr_out,

    //---- Receive Ports - Pattern Checker ports -----
    input   [LINK_WIDTH-1:0]    gt_rxprbscntreset_in,

    //---- Receive Ports - CDR Ports -----
    input   [LINK_WIDTH-1:0]    gt_rxcdrhold_in,

    //---- Receive Ports - Digital Monitor Ports -----
    output  [LINK_WIDTH*15-1:0] gt_dmonitorout_out,

    //---- Receive Ports - RX 8B/10B Decoder Ports -----
    //output  [LINK_WIDTH*4-1:0]  gt_rxdisperr_out,

    //---- Receive Ports - RX Byte and Word Alignment Ports -----
    output  [LINK_WIDTH-1:0]    gt_rxcommadet_out,

    // list of transceiver debug ports for GTH ends


    //____________________________COMMON PORTS________________________________
    input      gt_qplllock_in, // unconnected here
    input      gt_qplloutclk_in,
    input      gt_qplloutrefclk_in

);

//------------------------------------------------------------------------------
    wire                        gnd;
    wire [63:0]                 gnd_vec;
    wire                        vcc;
    wire                        tied_to_ground_i;

    wire [4:0]                  rxchanbondo0;
    wire                        gt_gtxreset_in;
    wire [LINK_WIDTH-1:0]       pll_lock;

    wire [LINK_WIDTH-1:0]       gt_rxresetdone_out_i;
    wire [LINK_WIDTH-1:0]       gt_txresetdone_out_i;
    wire [LINK_WIDTH*3-1:0]     gt_rxbufstatus_out_i;

    wire                        gt_userrdy_in;
    wire                        gt_rxbufreset_in;

    reg [9:0]                   reset_counter = 0; // initialized to 0 on GSR only
    reg [3:0]                   reset_pulse = 0;

    assign gnd                = 1'b0;
    assign tied_to_ground_i   = 1'b0;
    assign gnd_vec            = 64'h0000000000000000;
    assign vcc                = 1'b1;

    assign gt_rxbufreset_in   = gtrx_reset;
    assign gt_userrdy_in      = clk_lock && &pll_lock;
    assign gt_gtxreset_in     = (!reset_pulse[3] && &pll_lock) ? 1'b0 : 1'b1;
                              //reset_pulse[0] || (reset_counter[9] && (gt_pcs_rst || ~&pll_lock));

    assign gtrx_reset_done    = gt_rxresetdone_out_i & gt_txresetdone_out_i;
    assign gtrx_reset_req     = gt_rxbufstatus_out_i[5]
                             || gt_rxbufstatus_out_i[2];

    assign gt_rxresetdone_out = gt_rxresetdone_out_i;
    assign gt_txresetdone_out = gt_txresetdone_out_i;

    assign gt_rxbufstatus_out = gt_rxbufstatus_out_i;

//------------------------------------------------------------------
// update code for synchronizing the soft_reset with drp clock
reg [3:0] soft_reset_in_sync_srl;
wire      soft_reset_in_sync;

always @(posedge drpclk or posedge gt_pcs_rst) begin
  if (gt_pcs_rst) begin
    soft_reset_in_sync_srl <= 4'b1111;
  end else begin
    soft_reset_in_sync_srl <= {soft_reset_in_sync_srl[2:0], 1'b0};
  end
end

assign soft_reset_in_sync = soft_reset_in_sync_srl[3];
//------------------------------------------------------------------

//------------------------------------------------------------------------------
//-----------------------Init Wrapper Instatiation--------------------
    srio_gen2_5g_2x_16b_v7_gth_init #
    (
        .EXAMPLE_SIM_GTRESET_SPEEDUP    ("TRUE"),
        .EXAMPLE_SIMULATION             (0),
        .STABLE_CLOCK_PERIOD            (10),
        .EXAMPLE_USE_CHIPSCOPE          (0)
    )
    inst
    (
     .sysclk_in                             (drpclk),
     .soft_reset_in                         (soft_reset_in_sync),
     .dont_reset_on_data_error_in           (gnd),
     
	 .gt0_tx_fsm_reset_done_out             (),
     .gt0_rx_fsm_reset_done_out             (),
     .gt0_data_valid_in                     (1'b1),
     .gt0_tx_mmcm_lock_in                   (1'b1),
     .gt0_tx_mmcm_reset_out                 (),
	 .gt0_rx_mmcm_lock_in                   (1'b1),
	 .gt0_rx_mmcm_reset_out                 (),
    // applicable for 1.25, 2.5, 3.125@125, 3.125@156.25 configurations
     .gt0_drp_busy_out                      (),

     .gt1_tx_fsm_reset_done_out             (),
     .gt1_rx_fsm_reset_done_out             (),
     .gt1_data_valid_in                     (1'b1),
	 .gt1_tx_mmcm_lock_in                   (1'b1),
	 .gt1_tx_mmcm_reset_out                 (),
	 .gt1_rx_mmcm_lock_in                   (1'b1),
	 .gt1_rx_mmcm_reset_out                 (),
    // applicable for 1.25, 2.5, 3.125@125, 3.125@156.25 configurations
     .gt1_drp_busy_out                      (),

    //_________________________________________________________________________
    //GT0  (X0Y0)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt0_cpllfbclklost_out          (),                                     // output wire  gt0_cpllfbclklost_out
        .gt0_cplllock_out               (pll_lock[0]),                          // output wire  gt0_cplllock_out
        .gt0_cplllockdetclk_in          (drpclk),                               // input wire  gt0_cplllockdetclk_in
        .gt0_cpllreset_in               (gt_pcs_rst),                           // input wire  gt0_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt0_gtrefclk0_in               (refclk),                               // input wire  gt0_gtrefclk0_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt0_drpaddr_in                 (gt_drpaddr_in[8:0]),                   // input wire [8:0] gt0_drpaddr_in
        .gt0_drpclk_in                  (drpclk),                               // input wire  gt0_drpclk_in
        .gt0_drpdi_in                   (gt_drpdi_in[15:0]),                    // input wire [15:0] gt0_drpdi_in
        .gt0_drpdo_out                  (gt_drpdo_out[15:0]),                   // output wire [15:0] gt0_drpdo_out
        .gt0_drpen_in                   (gt_drpen_in[0]),                       // input wire  gt0_drpen_in
        .gt0_drprdy_out                 (gt_drprdy_out[0]),                     // output wire  gt0_drprdy_out
        .gt0_drpwe_in                   (gt_drpwe_in[0]),                       // input wire  gt0_drpwe_in
    //----------------------------- Loopback Ports -----------------------------
        .gt0_loopback_in                (gt_loopback_in[2:0]),                  // input wire [2:0] gt0_loopback_in
    //------------------- RX Initialization and Reset Ports --------------------
        .gt0_eyescanreset_in            (gt_eyescanreset_in[0]),                // input wire  gt0_eyescanreset_in
        .gt0_rxuserrdy_in               (gt_userrdy_in),                        // input wire  gt0_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt0_eyescandataerror_out       (gt_eyescandataerror_out[0]),           // output wire  gt0_eyescandataerror_out
        .gt0_eyescantrigger_in          (gt_eyescantrigger_in[0]),              // input wire  gt0_eyescantrigger_in
    //----------------------- Receive Ports - CDR Ports ------------------------
        .gt0_rxcdrhold_in               (gt_rxcdrhold_in[0]),                   // input wire  gt0_rxcdrhold_in
    //----------------- Receive Ports - Clock Correction Ports -----------------
        .gt0_rxclkcorcnt_out            (),                                     // output wire [1:0] gt0_rxclkcorcnt_out
    //----------------- Receive Ports - Digital Monitor Ports ------------------
        .gt0_dmonitorout_out            (gt_dmonitorout_out[14:0]),             // output wire [14:0] gt0_dmonitorout_out
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt0_rxusrclk_in                (gt_clk),                               //  (gt_pcs_clk),//(gt_clk),                               // input wire  gt0_rxusrclk_in
        .gt0_rxusrclk2_in               (gt_pcs_clk),                           // input wire  gt0_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt0_rxdata_out                 ({gtrx_data[7:0],gtrx_data[15:8],gtrx_data[23:16],gtrx_data[31:24]}),
                                                                                // output wire [31:0] gt0_rxdata_out
    //----------------- Receive Ports - Pattern Checker Ports ------------------
        .gt0_rxprbserr_out              (gt_rxprbserr_out[0]),                  // output wire  gt0_rxprbserr_out
        .gt0_rxprbssel_in               (gt_rxprbssel_in[2:0]),                 // input wire [2:0] gt0_rxprbssel_in
    //----------------- Receive Ports - Pattern Checker ports ------------------
        .gt0_rxprbscntreset_in          (gt_rxprbscntreset_in[0]),              // input wire  gt0_rxprbscntreset_in
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .gt0_rxdisperr_out              ({gtrx_disperr[0],gtrx_disperr[1],gtrx_disperr[2],gtrx_disperr[3]}),
                                                                                // output wire [3:0] gt0_rxdisperr_out
        .gt0_rxnotintable_out           ({gtrx_notintable[0],gtrx_notintable[1],gtrx_notintable[2],gtrx_notintable[3]}),
                                                                                // output wire [3:0] gt0_rxnotintable_out
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt0_gthrxn_in                  (srio_rxn0),                            // input wire  gt0_gthrxn_in
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .gt0_rxbufreset_in              (gt_rxbufreset_in),                     // input wire  gt0_rxbufreset_in
        .gt0_rxbufstatus_out            (gt_rxbufstatus_out_i[2:0]),            // output wire [2:0] gt0_rxbufstatus_out
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .gt0_rxbyteisaligned_out        (),                                     // output wire  gt0_rxbyteisaligned_out
        .gt0_rxbyterealign_out          (),                                     // output wire  gt0_rxbyterealign_out
        .gt0_rxcommadet_out             (gt_rxcommadet_out[0]),                 // output wire  gt0_rxcommadet_out
        .gt0_rxmcommaalignen_in         (vcc),                                  // input wire  gt0_rxmcommaalignen_in
        .gt0_rxpcommaalignen_in         (vcc),                                  // input wire  gt0_rxpcommaalignen_in
    //---------------- Receive Ports - RX Channel Bonding Ports ----------------
        .gt0_rxchanbondseq_out          (),                                     // output wire  gt0_rxchanbondseq_out
        .gt0_rxchbonden_in              (gtrx_chanbonden),                      // input wire  gt0_rxchbonden_in
        .gt0_rxchbondlevel_in           (3'b010),                               // input wire [2:0] gt0_rxchbondlevel_in
        .gt0_rxchbondmaster_in          (vcc),                                  // input wire  gt0_rxchbondmaster_in
        .gt0_rxchbondo_out              (rxchanbondo0),                         // output wire [4:0] gt0_rxchbondo_out
        .gt0_rxchbondslave_in           (gnd),                                  // input wire  gt0_rxchbondslave_in
    //--------------- Receive Ports - RX Channel Bonding Ports  ----------------
        .gt0_rxchanisaligned_out        (gtrx_chanisaligned[0]),                // output wire  gt0_rxchanisaligned_out
        .gt0_rxchanrealign_out          (),                                     // output wire  gt0_rxchanrealign_out
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt0_rxdfelpmreset_in           (gt_rxdfelpmreset_in[0]),               // input wire  gt0_rxdfelpmreset_in
        .gt0_rxmonitorout_out           (),                                     // output wire [6:0] gt0_rxmonitorout_out
        .gt0_rxmonitorsel_in            (gnd_vec[1:0]),                         // input wire [1:0] gt0_rxmonitorsel_in
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt0_gtrxreset_in               (gt_gtxreset_in),                       // input wire  gt0_gtrxreset_in
        .gt0_rxpcsreset_in              (gt_rxpcsreset_in[0]),                  // input wire  gt0_rxpcsreset_in
        .gt0_rxpmareset_in              (gt_rxpmareset_in[0]),                  // input wire  gt0_rxpmareset_in
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .gt0_rxlpmen_in                 (gt_rxlpmen_in[0]),                     // input wire  gt0_rxlpmen_in
    //--------------- Receive Ports - RX Polarity Control Ports ----------------
        .gt0_rxpolarity_in              (gt_rxpolarity_in[0]),                  // input wire  gt0_rxpolarity_in
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .gt0_rxchariscomma_out          ({gtrx_chariscomma[0],gtrx_chariscomma[1],gtrx_chariscomma[2],gtrx_chariscomma[3]}),
                                                                                // output wire [3:0] gt0_rxchariscomma_out
        .gt0_rxcharisk_out              ({gtrx_charisk[0],gtrx_charisk[1],gtrx_charisk[2],gtrx_charisk[3]}),
                                                                                // output wire [3:0] gt0_rxcharisk_out
    //---------------- Receive Ports - Rx Channel Bonding Ports ----------------
        .gt0_rxchbondi_in               (gnd_vec[4:0]),                         // input wire [4:0] gt0_rxchbondi_in
    //---------------------- Receive Ports -RX AFE Ports -----------------------
        .gt0_gthrxp_in                  (srio_rxp0),                            // input wire  gt0_gthrxp_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt0_rxresetdone_out            (gt_rxresetdone_out_i[0]),              // output wire  gt0_rxresetdone_out
    //---------------------- TX Configurable Driver Ports ----------------------
        .gt0_txpostcursor_in            (gt_txpostcursor_in[4:0]),              // input wire [4:0] gt0_txpostcursor_in
        .gt0_txprecursor_in             (gt_txprecursor_in[4:0]),               // input wire [4:0] gt0_txprecursor_in
    //------------------- TX Initialization and Reset Ports --------------------
        .gt0_gttxreset_in               (gt_gtxreset_in),                       // input wire  gt0_gttxreset_in
        .gt0_txuserrdy_in               (gt_userrdy_in),                        // input wire  gt0_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt0_txusrclk_in                (gt_clk),                               //  (gt_pcs_clk),//(gt_clk), // input wire  gt0_txusrclk_in
        .gt0_txusrclk2_in               (gt_pcs_clk),                           // input wire  gt0_txusrclk2_in
    //------------------- Transmit Ports - PCI Express Ports -------------------
        .gt0_txelecidle_in              (gnd),                                  // input wire  gt0_txelecidle_in
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .gt0_txprbsforceerr_in          (gt_txprbsforceerr_in[0]),              // input wire  gt0_txprbsforceerr_in
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .gt0_txbufstatus_out            (gt_txbufstatus_out[1:0]),              // output wire [1:0] gt0_txbufstatus_out
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .gt0_txdiffctrl_in              (gt0_txdiffctrl_in),                    // input wire [3:0] gt0_txdiffctrl_in
        .gt0_txinhibit_in               (gttx_inhibit[0]),                      // input wire  gt0_txinhibit_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt0_txdata_in                  ({gttx_data[7:0],gttx_data[15:8],gttx_data[23:16],gttx_data[31:24]}),
                                                                                // input wire [31:0] gt0_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt0_gthtxn_out                 (srio_txn0),                            // output wire  gt0_gthtxn_out
        .gt0_gthtxp_out                 (srio_txp0),                            // output wire  gt0_gthtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt0_txoutclk_out               (),                                     // output wire  gt0_txoutclk_out
        .gt0_txoutclkfabric_out         (),                                     // output wire  gt0_txoutclkfabric_out
        .gt0_txoutclkpcs_out            (),                                     // output wire  gt0_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt0_txpcsreset_in              (gt_txpcsreset_in[0]),                  // input wire  gt0_txpcsreset_in
        .gt0_txpmareset_in              (gt_txpmareset_in[0]),                  // input wire  gt0_txpmareset_in
        .gt0_txresetdone_out            (gt_txresetdone_out_i[0]),              // output wire  gt0_txresetdone_out
    //--------------- Transmit Ports - TX Polarity Control Ports ---------------
        .gt0_txpolarity_in              (gt_txpolarity_in[0]),                  // input wire  gt0_txpolarity_in
    //--------- Transmit Transmit Ports - 8b10b Encoder Control Ports ----------
        .gt0_txprbssel_in               (gt_txprbssel_in[2:0]),                 // input wire [2:0] gt0_txprbssel_in
    //--------- Transmit Transmit Ports - 8b10b Encoder Control Ports ----------
        .gt0_txcharisk_in               ({gttx_charisk[0],gttx_charisk[1],gttx_charisk[2],gttx_charisk[3]}),
                                                                                // input wire [3:0] gt0_txcharisk_in

    //GT1  (X0Y1)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt1_cpllfbclklost_out          (),                                     // output wire  gt1_cpllfbclklost_out
        .gt1_cplllock_out               (pll_lock[1]),                          // output wire  gt1_cplllock_out
        .gt1_cplllockdetclk_in          (drpclk),                               // input wire  gt1_cplllockdetclk_in
        .gt1_cpllreset_in               (gt_pcs_rst),                           // input wire  gt1_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt1_gtrefclk0_in               (refclk),                               // input wire  gt1_gtrefclk0_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt1_drpaddr_in                 (gt_drpaddr_in[17:9]),                  // input wire [8:0] gt1_drpaddr_in
        .gt1_drpclk_in                  (drpclk),                               // input wire  gt1_drpclk_in
        .gt1_drpdi_in                   (gt_drpdi_in[31:16]),                   // input wire [15:0] gt1_drpdi_in
        .gt1_drpdo_out                  (gt_drpdo_out[31:16]),                  // output wire [15:0] gt1_drpdo_out
        .gt1_drpen_in                   (gt_drpen_in[1]),                       // input wire  gt1_drpen_in
        .gt1_drprdy_out                 (gt_drprdy_out[1]),                     // output wire  gt1_drprdy_out
        .gt1_drpwe_in                   (gt_drpwe_in[1]),                       // input wire  gt1_drpwe_in
    //----------------------------- Loopback Ports -----------------------------
        .gt1_loopback_in                (gt_loopback_in[5:3]),                  // input wire [2:0] gt1_loopback_in
    //------------------- RX Initialization and Reset Ports --------------------
        .gt1_eyescanreset_in            (gt_eyescanreset_in[1]),                // input wire  gt1_eyescanreset_in
        .gt1_rxuserrdy_in               (gt_userrdy_in),                        // input wire  gt1_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt1_eyescandataerror_out       (gt_eyescandataerror_out[1]),           // output wire  gt1_eyescandataerror_out
        .gt1_eyescantrigger_in          (gt_eyescantrigger_in[1]),              // input wire  gt1_eyescantrigger_in
    //----------------------- Receive Ports - CDR Ports ------------------------
        .gt1_rxcdrhold_in               (gt_rxcdrhold_in[1]),                   // input wire  gt1_rxcdrhold_in
    //----------------- Receive Ports - Clock Correction Ports -----------------
        .gt1_rxclkcorcnt_out            (),                                     // output wire [1:0] gt1_rxclkcorcnt_out
    //----------------- Receive Ports - Digital Monitor Ports ------------------
        .gt1_dmonitorout_out            (gt_dmonitorout_out[29:15]),            // output wire [14:0] gt1_dmonitorout_out
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt1_rxusrclk_in                (gt_clk),                               //  (gt_pcs_clk),//(gt_clk),                               // input wire  gt1_rxusrclk_in
        .gt1_rxusrclk2_in               (gt_pcs_clk),                           // input wire  gt1_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt1_rxdata_out                 ({gtrx_data[39:32],gtrx_data[47:40],gtrx_data[55:48],gtrx_data[63:56]}),
                                                                                // output wire [31:0] gt1_rxdata_out
    //----------------- Receive Ports - Pattern Checker Ports ------------------
        .gt1_rxprbserr_out              (gt_rxprbserr_out[1]),                  // output wire  gt1_rxprbserr_out
        .gt1_rxprbssel_in               (gt_rxprbssel_in[5:3]),                 // input wire [2:0] gt1_rxprbssel_in
    //----------------- Receive Ports - Pattern Checker ports ------------------
        .gt1_rxprbscntreset_in          (gt_rxprbscntreset_in[1]),              // input wire  gt1_rxprbscntreset_in
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .gt1_rxdisperr_out              ({gtrx_disperr[4],gtrx_disperr[5],gtrx_disperr[6],gtrx_disperr[7]}),
                                                                                // output wire [3:0] gt1_rxdisperr_out
        .gt1_rxnotintable_out           ({gtrx_notintable[4],gtrx_notintable[5],gtrx_notintable[6],gtrx_notintable[7]}),
                                                                                // output wire [3:0] gt1_rxnotintable_out
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt1_gthrxn_in                  (srio_rxn1),                            // input wire  gt1_gthrxn_in
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .gt1_rxbufreset_in              (gt_rxbufreset_in),                     // input wire  gt1_rxbufreset_in
        .gt1_rxbufstatus_out            (gt_rxbufstatus_out_i[5:3]),            // output wire [2:0] gt1_rxbufstatus_out
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .gt1_rxbyteisaligned_out        (),                                     // output wire  gt1_rxbyteisaligned_out
        .gt1_rxbyterealign_out          (),                                     // output wire  gt1_rxbyterealign_out
        .gt1_rxcommadet_out             (gt_rxcommadet_out[1]),                 // output wire  gt1_rxcommadet_out
        .gt1_rxmcommaalignen_in         (vcc),                                  // input wire  gt1_rxmcommaalignen_in
        .gt1_rxpcommaalignen_in         (vcc),                                  // input wire  gt1_rxpcommaalignen_in
    //---------------- Receive Ports - RX Channel Bonding Ports ----------------
        .gt1_rxchanbondseq_out          (),                                     // output wire  gt1_rxchanbondseq_out
        .gt1_rxchbonden_in              (gtrx_chanbonden),                      // input wire  gt1_rxchbonden_in
        .gt1_rxchbondlevel_in           (3'b001),                               // input wire [2:0] gt1_rxchbondlevel_in
        .gt1_rxchbondmaster_in          (gnd),                                  // input wire  gt1_rxchbondmaster_in
        .gt1_rxchbondo_out              (),                                     // output wire [4:0] gt1_rxchbondo_out
        .gt1_rxchbondslave_in           (vcc),                                  // input wire  gt1_rxchbondslave_in
    //--------------- Receive Ports - RX Channel Bonding Ports  ----------------
        .gt1_rxchanisaligned_out        (gtrx_chanisaligned[1]),                // output wire  gt1_rxchanisaligned_out
        .gt1_rxchanrealign_out          (),                                     // output wire  gt1_rxchanrealign_out
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt1_rxdfelpmreset_in           (gt_rxdfelpmreset_in[1]),               // input wire  gt1_rxdfelpmreset_in
        .gt1_rxmonitorout_out           (),                                     // output wire [6:0] gt1_rxmonitorout_out
        .gt1_rxmonitorsel_in            (gnd_vec[1:0]),                         // input wire [1:0] gt1_rxmonitorsel_in
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt1_gtrxreset_in               (gt_gtxreset_in),                       // input wire  gt1_gtrxreset_in
        .gt1_rxpcsreset_in              (gt_rxpcsreset_in[1]),                  // input wire  gt1_rxpcsreset_in
        .gt1_rxpmareset_in              (gt_rxpmareset_in[1]),                  // input wire  gt1_rxpmareset_in
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .gt1_rxlpmen_in                 (gt_rxlpmen_in[1]),                     // input wire  gt1_rxlpmen_in
    //--------------- Receive Ports - RX Polarity Control Ports ----------------
        .gt1_rxpolarity_in              (gt_rxpolarity_in[1]),                  // input wire  gt1_rxpolarity_in
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .gt1_rxchariscomma_out          ({gtrx_chariscomma[4],gtrx_chariscomma[5],gtrx_chariscomma[6],gtrx_chariscomma[7]}),
                                                                                // output wire [3:0] gt1_rxchariscomma_out
        .gt1_rxcharisk_out              ({gtrx_charisk[4],gtrx_charisk[5],gtrx_charisk[6],gtrx_charisk[7]}),
                                                                                // output wire [3:0] gt1_rxcharisk_out
    //---------------- Receive Ports - Rx Channel Bonding Ports ----------------
        .gt1_rxchbondi_in               (rxchanbondo0),                         // input wire [4:0] gt1_rxchbondi_in
    //---------------------- Receive Ports -RX AFE Ports -----------------------
        .gt1_gthrxp_in                  (srio_rxp1),                            // input wire  gt1_gthrxp_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt1_rxresetdone_out            (gt_rxresetdone_out_i[1]),              // output wire  gt1_rxresetdone_out
    //---------------------- TX Configurable Driver Ports ----------------------
        .gt1_txpostcursor_in            (gt_txpostcursor_in[9:5]),              // input wire [4:0] gt1_txpostcursor_in
        .gt1_txprecursor_in             (gt_txprecursor_in[9:5]),               // input wire [4:0] gt1_txprecursor_in
    //------------------- TX Initialization and Reset Ports --------------------
        .gt1_gttxreset_in               (gt_gtxreset_in),                       // input wire  gt1_gttxreset_in
        .gt1_txuserrdy_in               (gt_userrdy_in),                        // input wire  gt1_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt1_txusrclk_in                (gt_clk),                               //  (gt_pcs_clk),//(gt_clk), // input wire  gt1_txusrclk_in
        .gt1_txusrclk2_in               (gt_pcs_clk),                           // input wire  gt1_txusrclk2_in
    //------------------- Transmit Ports - PCI Express Ports -------------------
        .gt1_txelecidle_in              (gnd),                                  // input wire  gt1_txelecidle_in
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .gt1_txprbsforceerr_in          (gt_txprbsforceerr_in[1]),              // input wire  gt1_txprbsforceerr_in
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .gt1_txbufstatus_out            (gt_txbufstatus_out[3:2]),              // output wire [1:0] gt1_txbufstatus_out
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .gt1_txdiffctrl_in              (gt1_txdiffctrl_in),                    // input wire [3:0] gt1_txdiffctrl_in
        .gt1_txinhibit_in               (gttx_inhibit[1]),                      // input wire  gt1_txinhibit_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt1_txdata_in                  ({gttx_data[39:32],gttx_data[47:40],gttx_data[55:48],gttx_data[63:56]}),
                                                                                // input wire [31:0] gt1_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt1_gthtxn_out                 (srio_txn1),                            // output wire  gt1_gthtxn_out
        .gt1_gthtxp_out                 (srio_txp1),                            // output wire  gt1_gthtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt1_txoutclk_out               (),                                     // output wire  gt1_txoutclk_out
        .gt1_txoutclkfabric_out         (),                                     // output wire  gt1_txoutclkfabric_out
        .gt1_txoutclkpcs_out            (),                                     // output wire  gt1_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt1_txpcsreset_in              (gt_txpcsreset_in[1]),                  // input wire  gt1_txpcsreset_in
        .gt1_txpmareset_in              (gt_txpmareset_in[1]),                  // input wire  gt1_txpmareset_in
        .gt1_txresetdone_out            (gt_txresetdone_out_i[1]),              // output wire  gt1_txresetdone_out
    //--------------- Transmit Ports - TX Polarity Control Ports ---------------
        .gt1_txpolarity_in              (gt_txpolarity_in[1]),                  // input wire  gt1_txpolarity_in
    //---------------- Transmit Ports - pattern Generator Ports ----------------
        .gt1_txprbssel_in               (gt_txprbssel_in[5:3]),                 // input wire [2:0] gt1_txprbssel_in
    //--------- Transmit Transmit Ports - 8b10b Encoder Control Ports ----------
        .gt1_txcharisk_in               ({gttx_charisk[4],gttx_charisk[5],gttx_charisk[6],gttx_charisk[7]}),
                                                                                // input wire [3:0] gt1_txcharisk_in


    //____________________________COMMON PORTS________________________________
     .gt0_qplloutclk_in                 (gt_qplloutclk_in),
     .gt0_qplloutrefclk_in              (gt_qplloutrefclk_in)
    );

//------------------------------------------------------------------------------

    //***********************************************************************//
    //                                                                       //
    //---------------------  Reset Logic  -----------------------------------//
    //                                                                       //
    //***********************************************************************//

    // Upon configuration, GTXTXRESET and GTXRXRESET must be initiated in
    // Sequential mode. None of the GT resets (CPLLRESET, QPLLRESET,
    // GTXTXRESET and GTXRXRESET) can be asserted until a minimum of 500ns
    // after GSR.

      always @(posedge gt_pcs_clk)
      begin
         if (clk_lock && !reset_counter[9])
            reset_counter   <=   #TCQ reset_counter + 1'b1;
      end

      always @(posedge gt_pcs_clk)
      begin
         if(!reset_counter[9])
            reset_pulse   <=   #TCQ 4'b1110;

         else
           // reset_pulse   <=   #TCQ {1'b0, reset_pulse[3:1]};
            reset_pulse   <=   #TCQ {reset_pulse[2:0], 1'b0};

      end

//------------------------------------------------------------------------------

endmodule

