// HongXin Copyright 2010~2019
// HongXin Company Confidential
// Company : HongXin Telecom .Inc
// Copyright(c) 2019, HongXin Telecom .Inc, All right reserved

//---------------------------------------------------------------------
// AUTHOR          : Tang Dongsheng
//---------------------------------------------------------------------
// Tool version    : ISE14.7 / Vivado 2015
//---------------------------------------------------------------------
// Release History :
//---------------------------------------------------------------------
// Version    |    Date      | Description
//---------------------------------------------------------------------
// 1.0-0      |  2015-05-15  | first edit
// 1.1-0      |  2018-08-01  | support different read and write data width
// 1.2-0      |  2019-08-02  | a.add the new features of ram_sdp module
//                             b.change write reset and read reset port
//---------------------------------------------------------------------
// Main Function   :
// 1. 用代码的形式实现了FIFO
// 2. 读写时钟独立，支持同步和异步模式
// 3. FIFO的数据宽度和地址宽度可参数化
// 4. 支持First Word Fall Through模式
// 5. 支持不同的读写数据位宽
//---------------------------------------------------------------------
`timescale 1ns / 1ps

module fifo #
(
    parameter DATA_WIDTH      = 32    ,//FIFO的数据宽度
    parameter ADDR_WIDTH      = 10    ,//FIFO的地址宽度
    parameter DIFF_ADDR_WIDTH = 0     ,//表示读地址宽度与写地址宽度的差值（可以为负数）
    parameter SYNC_MODE       = 1     ,//FIFO的模式。1为同步模式，即读时钟和写时钟为同一个时钟；0为异步模式，即读时钟和写时钟不一样
    parameter FWFT            = 0     ,//Active High. For Xilinx: First Word Fall Through; For Altera: Show-ahead FIFO mode
    parameter MEM_STYLE       = "AUTO",//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM"
    
    //auto generated by the parama above, no need to allocate
    parameter RD_DATA_WIDTH = DATA_WIDTH*(2**ADDR_WIDTH)/2**(ADDR_WIDTH+DIFF_ADDR_WIDTH)
)
(
    input                                 I_fifo_rst     ,//FIFO的复位
    
    input                                 I_fifo_wr_clk  ,//FIFO的写时钟
    input                                 I_fifo_wr_en   ,//FIFO的写使能
    input  [DATA_WIDTH-1:0]               I_fifo_wr_data ,//FIFO的写数据,同步于I_fifo_wr_en
    output [ADDR_WIDTH :0]                O_fifo_wr_cnt  ,//FIFO中剩余的数据个数,自然数
    output                                O_fifo_full    ,//FIFO满了
    
    input                                 I_fifo_rd_clk  ,//FIFO的读时钟
    input                                 I_fifo_rd_en   ,//FIFO的读使能
    output                                O_fifo_rd_valid,//FIFO的读数据有效指示
    output [RD_DATA_WIDTH-1:0]            O_fifo_rd_data ,//FIFO的读数据
    output [ADDR_WIDTH+DIFF_ADDR_WIDTH:0] O_fifo_rd_cnt  ,//FIFO中剩余的数据个数,自然数
    output                                O_fifo_empty    //FIFO空了
);
    
    localparam OVERRIDE = 1;//当FIFO满时，如果继续写入数据，是否将旧值覆盖（写指针不动）。1：覆盖，0：不覆盖，即将新数据丢弃。为1时更有利于写时序
    
    reg [1:0] rst_buf;
    always @ (posedge I_fifo_rd_clk)
    begin
        rst_buf <= {rst_buf[0],I_fifo_rst};
    end
    
    wire wr_rst;
    wire rd_rst;
    assign wr_rst = I_fifo_rst;
    assign rd_rst = SYNC_MODE ? I_fifo_rst : rst_buf[1];
    
    wire                                  s_fifo_rd_en   ;
    wire                                  s_fifo_rd_valid;
    wire [RD_DATA_WIDTH-1:0]              s_fifo_rd_data ;
    wire [ADDR_WIDTH+DIFF_ADDR_WIDTH:0]   s_fifo_rd_cnt  ;
    wire                                  s_fifo_empty   ;
    
	wire                                  s_ram_wr_clk   ;
	wire                                  s_ram_wr_en    ;
	wire [ADDR_WIDTH-1:0]                 s_ram_wr_addr  ;
	wire [DATA_WIDTH-1:0]                 s_ram_wr_data  ;
	wire                                  s_ram_rd_clk   ;
	wire                                  s_ram_rd_en    ;
	wire [ADDR_WIDTH+DIFF_ADDR_WIDTH-1:0] s_ram_rd_addr  ;
	wire [RD_DATA_WIDTH-1:0]              s_ram_rd_data  ;
    fifo_ctrl #
    (
        .DATA_WIDTH     (DATA_WIDTH     ),//FIFO的数据宽度
        .ADDR_WIDTH     (ADDR_WIDTH     ),//FIFO的地址宽度
        .DIFF_ADDR_WIDTH(DIFF_ADDR_WIDTH),//表示读地址宽度与写地址宽度的差值（可以为负数）
        .SYNC_MODE      (SYNC_MODE      ),//FIFO的模式。1为同步模式，即读时钟和写时钟为同一个时钟；0为异步模式，即读时钟和写时钟不一样
        .OVERRIDE       (OVERRIDE       ) //当FIFO满时，如果继续写入数据，是否将旧值覆盖（写指针不动）。1：覆盖，0：不覆盖，即将新数据丢弃。为1时更有利于写时序
    )
    u_fifo_ctrl
    (
        .I_wr_rst       (wr_rst         ),//FIFO的写同步复位
        .I_rd_rst       (rd_rst         ),//FIFO的读同步复位
        
        .I_fifo_wr_clk  (I_fifo_wr_clk  ),//FIFO的写时钟
        .I_fifo_wr_en   (I_fifo_wr_en   ),//FIFO的写使能
        .I_fifo_wr_data (I_fifo_wr_data ),//FIFO的写数据,同步于I_fifo_wr_en
        .O_fifo_wr_cnt  (O_fifo_wr_cnt  ),//FIFO中剩余的数据个数,自然数
        .O_fifo_full    (O_fifo_full    ),//FIFO满了
        
        .I_fifo_rd_clk  (I_fifo_rd_clk  ),//FIFO的读时钟
        .I_fifo_rd_en   (s_fifo_rd_en   ),//FIFO的读使能
        .O_fifo_rd_valid(s_fifo_rd_valid),//FIFO的读数据有效指示
        .O_fifo_rd_data (s_fifo_rd_data ),//FIFO的读数据,直接连RAM的输出
        .O_fifo_rd_cnt  (s_fifo_rd_cnt  ),//FIFO中剩余的数据个数,自然数
        .O_fifo_empty   (s_fifo_empty   ),//FIFO空了
        
        .O_ram_wr_clk   (s_ram_wr_clk   ),
        .O_ram_wr_en    (s_ram_wr_en    ),
        .O_ram_wr_addr  (s_ram_wr_addr  ),
        .O_ram_wr_data  (s_ram_wr_data  ),
        .O_ram_rd_clk   (s_ram_rd_clk   ),
        .O_ram_rd_en    (s_ram_rd_en    ),
        .O_ram_rd_addr  (s_ram_rd_addr  ),
        .I_ram_rd_data  (s_ram_rd_data  ) 
    );
    
    ram_sdp #
    (
        .ADDR_WIDTH     (ADDR_WIDTH     ),
        .DATA_WIDTH     (DATA_WIDTH     ),
        .REG_OUT        (1              ),//It's highly recommended to set this parama bigger than '0'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
        .MEM_STYLE      (MEM_STYLE      ),//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
        .USE_RD_EN      (!FWFT          ),//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
        .DIFF_ADDR_WIDTH(DIFF_ADDR_WIDTH) //Negetive value means the read data width is 2^N base than write data. Posetive value means the write data width is 2^N base than read data.
    )
    u_ram_sdp
    (
        .I_wr_clk (s_ram_wr_clk ),
        .I_wr_en  (s_ram_wr_en  ),
        .I_wr_addr(s_ram_wr_addr),
        .I_wr_data(s_ram_wr_data),   
        .I_rd_clk (s_ram_rd_clk ),
        .I_rd_en  (s_ram_rd_en  ),
        .I_rd_addr(s_ram_rd_addr),
        .O_rd_data(s_ram_rd_data)
    );
    
    generate
        if(FWFT==0)
            begin : normal
                assign s_fifo_rd_en    = I_fifo_rd_en   ;
                assign O_fifo_rd_valid = s_fifo_rd_valid;
                assign O_fifo_rd_data  = s_fifo_rd_data ;
                assign O_fifo_rd_cnt   = s_fifo_rd_cnt  ;
                assign O_fifo_empty    = s_fifo_empty   ;
            end
        else
            begin : fwft
                
                fwft_ctrl #
                (
		            .DATA_WIDTH(RD_DATA_WIDTH             ),//RAM的读数据宽度
		            .ADDR_WIDTH(ADDR_WIDTH+DIFF_ADDR_WIDTH) //RAM的读地址宽度
                )
                u_fwft_ctrl
                (
		            .I_rst          (rd_rst         ),
		            .I_clk          (I_fifo_rd_clk  ),
		            
		            .O_fifo_rd_en   (s_fifo_rd_en   ),
		            .I_fifo_rd_valid(s_fifo_rd_valid),
		            .I_fifo_rd_data (s_fifo_rd_data ),
		            .I_fifo_rd_cnt  (s_fifo_rd_cnt  ),
		            .I_fifo_empty   (s_fifo_empty   ),
		            
		            .I_fwft_rd_en   (I_fifo_rd_en   ),
		            .O_fwft_rd_valid(O_fifo_rd_valid),
		            .O_fwft_rd_data (O_fifo_rd_data ),
		            .O_fwft_rd_cnt  (O_fifo_rd_cnt  ),
		            .O_fwft_empty   (O_fifo_empty   )
                );
                
            end
    endgenerate
    
endmodule
