// HongXin Copyright 2010~2019
// HongXin Company Confidential
// Company : HongXin Telecom .Inc
// Copyright(c) 2019, HongXin Telecom .Inc, All right reserved

//---------------------------------------------------------------------
// AUTHOR          : Tang Dongsheng
//---------------------------------------------------------------------
// Tool version    : ISE14.7 / Vivado 2018 / Quartus 20.1
//---------------------------------------------------------------------
// Release History :
//---------------------------------------------------------------------
// Version    |    Date      | Description
//---------------------------------------------------------------------
// 1.0-0      |  2015-05-15  | first edit
// 1.1-0      |  2018-08-01  | support different read and write data width
// 1.2-0      |  2020-07-21  | support altera M20K/M9K byte write mode
// 1.3-0      |  2020-09-09  | support xilinx URAM288
//---------------------------------------------------------------------
// Main Function   :
// 1. 用代码实现一个简单双口RAM
// 2. 支持实现RAM方式的可参数化，支持Altera和Xilinx环境
// 3. RAM的数据宽度和地址宽度可参数化
//---------------------------------------------------------------------
`timescale 1ns / 1ps

module ram_sdp_base #
(//sdp : Simple Dual Port
    parameter ADDR_WIDTH        =      9,
    parameter DATA_WIDTH        =     18,
    parameter REG_OUT           =      1,//0<=REG_OUT<=2. It's highly recommended to set this parama bigger than '0'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
    parameter MEM_STYLE         = "AUTO",//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
    parameter USE_RD_EN         =      0,//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
    parameter COL_NUM           =      1,//Number of byte write enable bit
    
    //auto generated by the parama above, no need to allocate
    parameter FULL_DATA_WIDTH  = DATA_WIDTH*COL_NUM
)
(
    input                        I_wr_clk ,
    input  [COL_NUM-1:0]         I_wr_en  ,
    input  [ADDR_WIDTH-1:0]      I_wr_addr,
    input  [FULL_DATA_WIDTH-1:0] I_wr_data,
    input                        I_rd_clk ,
    input                        I_rd_en  ,
    input  [ADDR_WIDTH-1:0]      I_rd_addr,
    output [FULL_DATA_WIDTH-1:0] O_rd_data
);
    
    function integer div_round
    (
        input integer a,
        input integer b
    );
    begin
        div_round = (a/b) + ((a%b)!=0);
    end
    endfunction
    
    localparam ALTERA_RAM = (MEM_STYLE=="M20K")||(MEM_STYLE=="M9K");
    localparam ALTERA_SYNCRAM_FORCE = (COL_NUM>1 && ALTERA_RAM);
    
    genvar i,j,k;
    generate
        
        if(ALTERA_SYNCRAM_FORCE)//Altera RAM的Byte Write功能目前通过调IP实现。手写暂不支持
            begin: syncram_force
                
                //此分支在运用上的限制:
                //1. 1<=REG_OUT<=2
                //2. 支持Byte Write时(即COL_NUM>1)，DATA_WIDTH需为8或9或10的整数倍
                //3. MEM_STYLE=="SYNCRAM_FORCE"且COL_NUM==1时，可能会引起资源浪费。
                //   比如DATA_WIDTH==35时，内部计算BYTE_SIZE为8，实则没有9划算。
                //   此时建议运用上将35改成36，或者修改MEM_STYLE走其它分支
                
                ram_sdp_base_altera #
                (
                    .ADDR_WIDTH(ADDR_WIDTH),
                    .DATA_WIDTH(DATA_WIDTH),
                    .REG_OUT   (REG_OUT   ),//1<=REG_OUT<=2
                    .MEM_STYLE (MEM_STYLE ),//use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
                    .USE_RD_EN (USE_RD_EN ),//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
                    .COL_NUM   (COL_NUM   ) //Number of byte write enable bit
                )
                u_ram_sdp_base_altera
                (
                    .I_wr_clk (I_wr_clk ),
                    .I_wr_en  (I_wr_en  ),
                    .I_wr_addr(I_wr_addr),
                    .I_wr_data(I_wr_data),
                    .I_rd_clk (I_rd_clk ),
                    .I_rd_en  (I_rd_en  ),
                    .I_rd_addr(I_rd_addr),
                    .O_rd_data(O_rd_data)
                );
                
            end
    
        else if(MEM_STYLE=="URAM_FORCE")
            begin : uram_force
                
                //此分支在运用上的限制:
                //1. 1<=REG_OUT<=2
                //2. 支持Byte Write时(即COL_NUM>1)，DATA_WIDTH需为8或9的整数倍
                //3. 读写时钟需为同一个
                //4. URAM288的深度为1024，宽度72bit，不可调。
                //   深度和宽度超范围时，需要在外层加逻辑实现多个URAM的拼接（下面已实现）。
                
                localparam M = (ADDR_WIDTH>12) ? (ADDR_WIDTH-12) : 0;//用2^M个URAM纵向拼接，增加深度
                localparam N = div_round(COL_NUM*DATA_WIDTH,72);//用N个URAM横向拼接，增加宽度
                
                localparam DATA_WIDTH_S = (DATA_WIDTH%9==0) ? 9 : 8;
                localparam COL_NUM_S = 72/DATA_WIDTH_S;
                localparam REG_OUT_S = (REG_OUT==2&&M>0) ? 1 : REG_OUT;
                
                wire [M+11:0] wr_addr;
                wire [M+11:0] rd_addr;
                wire [N*72-1:0] wr_data           ;
                wire [N*72-1:0] rd_data [2**M-1:0];
                
                //二者位宽不一致时，高位自动补0
                assign wr_addr   = I_wr_addr;
                assign rd_addr   = I_rd_addr;
                assign wr_data   = I_wr_data;
                
                localparam W = div_round(DATA_WIDTH,DATA_WIDTH_S);//1个I_wr_en的bit可对应W个byte_wr_en的bit
                wire [N*COL_NUM_S-1:0] byte_wr_en;
                for(k=0;k<N*COL_NUM_S;k=k+1)                 //这段代码可能不易理解
                begin:bwr                                    //其效果是：
                    if((k/W)<COL_NUM)                        //将I_wr_en的每个bit扩展W份，
                        assign byte_wr_en[k] = I_wr_en[k/W];//作为URAM的写字节使能，
                    else                                    //
                        assign byte_wr_en[k] = 1'b0;        //扩展后位宽不够的，高位补0
                end
                
                if(M==0)
                    begin:m0
                        assign O_rd_data = rd_data[0];
                    end
                else 
                    begin:mx
                        
                        reg  [M+11:12] rd_addr_h;
                        always @ (posedge I_rd_clk)
                        begin
                            if(!USE_RD_EN)
                                rd_addr_h <= wr_addr[M+11:12];
                            else if(I_rd_en)
                                rd_addr_h <= wr_addr[M+11:12];
                        end
                        
                        if(REG_OUT==2)
                            begin:r2
                                reg  [N*72-1:0] rd_data_s;
                                always @ (posedge I_rd_clk)
                                begin
                                    rd_data_s = rd_data[rd_addr_h];
                                end
                                assign O_rd_data = rd_data_s;
                            end
                        else
                            begin:r1//此分支的时序稍差
                                assign O_rd_data = rd_data[rd_addr_h];
                            end
                    end
                
                wire [2**M-1:0] wr_cs;
                
                for(i=0;i<2**M;i=i+1)
                begin:depth
                    
                    if(M==0)
                        begin:m0
                            assign wr_cs[i] = 1'b1;
                        end
                    else
                        begin:mx
                            assign wr_cs[i] = (wr_addr[M+11:12]==i);
                        end
                    
                    for(j=0;j<N;j=j+1)
                    begin:width
                        
                        ram_sdp_base_uram #
                        (
                            .DATA_WIDTH(DATA_WIDTH_S),//DATA_WIDTH*COL_NUM should be less or equal to 72,and DATA_WIDTH/8 or DATA_WIDTH/9 is an interger
                            .REG_OUT   (REG_OUT_S   ),//1<=REG_OUT<=2
                            .USE_RD_EN (USE_RD_EN   ),//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
                            .COL_NUM   (COL_NUM_S   ) //Number of byte write enable bit
                        )
                        u_ram_sdp_base_uram
                        (
                            .I_wr_clk (I_wr_clk                     ),
                            .I_wr_en  (byte_wr_en[j*COL_NUM_S+:COL_NUM_S]&{COL_NUM_S{wr_cs[i]}}),
                            .I_wr_addr(wr_addr[11:0]                ),
                            .I_wr_data(wr_data[72*j+:72]            ),
                            .I_rd_clk (I_rd_clk                     ),
                            .I_rd_en  (I_rd_en                      ),
                            .I_rd_addr(rd_addr[11:0]                ),
                            .O_rd_data(rd_data[i][72*j+:72]         )
                        );
                        
                    end
                end
                
                
            end
    
        else
            
            begin : common
                
                //此分支在运用上的限制:
                //1. 如果MEM_STYLE采用Xilinx或者Altera的专用RAM资源，1<=REG_OUT<=2。
                //   如果用逻辑资源搭建RAM，REG_OUT可以为0。
                //2. Altara专用RAM无法通过此分支实现Byte Write，使用时请传递正确的MEM_STYLE参数。
                //   否则可能会采用逻辑资源实现，或者导致使用更多的M20K/M9K。
                //3. Xilinx BRAM/URAM支持Byte Write时(即COL_NUM>1)，DATA_WIDTH需要是8或9的整数倍。
                //4. 由于采用通用的RAM描述方法，对Primitive/LPM的某些特性支持不全（依赖于综合工具）。
                
                ram_sdp_base_common #
                (
                    .ADDR_WIDTH(ADDR_WIDTH),
                    .DATA_WIDTH(DATA_WIDTH),
                    .REG_OUT   (REG_OUT   ),//0<=REG_OUT<=2. It's highly recommended to set this parama bigger than '0'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
                    .MEM_STYLE (MEM_STYLE ),//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
                    .USE_RD_EN (USE_RD_EN ),//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
                    .COL_NUM   (COL_NUM   ) //Number of byte write enable bit
                )
                u_ram_sdp_base_common
                (
                    .I_wr_clk (I_wr_clk ),
                    .I_wr_en  (I_wr_en  ),
                    .I_wr_addr(I_wr_addr),
                    .I_wr_data(I_wr_data),
                    .I_rd_clk (I_rd_clk ),
                    .I_rd_en  (I_rd_en  ),
                    .I_rd_addr(I_rd_addr),
                    .O_rd_data(O_rd_data) 
                );
            end
            
    endgenerate
    
endmodule
