// HongXin Copyright 2010~2019
// HongXin Company Confidential
// Company : HongXin Telecom .Inc
// Copyright(c) 2019, HongXin Telecom .Inc, All right reserved

//---------------------------------------------------------------------
// AUTHOR          : Tang Dongsheng
//---------------------------------------------------------------------
// Tool version    : Quartus 20.1
//---------------------------------------------------------------------
// Release History :
//---------------------------------------------------------------------
// Version    |    Date      | Description
//---------------------------------------------------------------------
// 1.0-0      |  2020-09-09  | first edit
//---------------------------------------------------------------------
// Main Function   :
// 1. 用altera_syncram实现简单双口RAM
//---------------------------------------------------------------------
`timescale 1ns / 1ps

module ram_sdp_base_altera #
(//sdp : Simple Dual Port
    parameter ADDR_WIDTH        =      9,
    parameter DATA_WIDTH        =     18,
    parameter REG_OUT           =      1,//1<=REG_OUT<=2
    parameter MEM_STYLE         = "M20K",//use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
    parameter USE_RD_EN         =      0,//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
    parameter COL_NUM           =      1,//Number of byte write enable bit
    
    //auto generated by the parama above, no need to allocate
    parameter FULL_DATA_WIDTH  = DATA_WIDTH*COL_NUM
)
(
    input                        I_wr_clk ,
    input  [COL_NUM-1:0]         I_wr_en  ,
    input  [ADDR_WIDTH-1:0]      I_wr_addr,
    input  [FULL_DATA_WIDTH-1:0] I_wr_data,
    input                        I_rd_clk ,
    input                        I_rd_en  ,
    input  [ADDR_WIDTH-1:0]      I_rd_addr,
    output [FULL_DATA_WIDTH-1:0] O_rd_data
);
    
    function integer div_round
    (
        input integer a,
        input integer b
    );
    begin
        div_round = (a/b) + ((a%b)!=0);
    end
    endfunction
    
    
    localparam BYTE_SIZE = (DATA_WIDTH%10==0) ? 10  :
                           (DATA_WIDTH%9 ==0) ? 9 : 8;
    
    localparam OUTDATA_REG_B   = (REG_OUT>1) ? "CLOCK1" : "UNREGISTERED";
    localparam N = div_round(DATA_WIDTH,BYTE_SIZE);//COL_NUM>1时，要求DATA_WIDTH一定是BYTE_SIZE的整数倍
    localparam WIDTH_BYTEENA_A = div_round(FULL_DATA_WIDTH,BYTE_SIZE);
    
    wire [WIDTH_BYTEENA_A-1:0] byteena_a;
    genvar i;
    generate
        for(i=0;i<COL_NUM;i=i+1)
        begin:col//将I_wr_en的每个bit扩展N份
            assign byteena_a[i*N+:N] = {N{I_wr_en[i]}};
        end
    endgenerate
    
    wire rd_en;
    assign rd_en = USE_RD_EN ? I_rd_en : 1'b1;
    
    wire [FULL_DATA_WIDTH-1:0] data_b;
    assign data_b = {FULL_DATA_WIDTH{1'b1}};
    
    altera_syncram  #
    (
        .address_aclr_b        ("NONE"          ),
        .address_reg_b         ("CLOCK1"        ),
        .byte_size             (BYTE_SIZE       ),
        .clock_enable_input_a  ("BYPASS"        ),
        .clock_enable_input_b  ("BYPASS"        ),
        .clock_enable_output_b ("BYPASS"        ),
        .intended_device_family("Stratix 10"    ),
        .lpm_type              ("altera_syncram"),
        .numwords_a            (2**ADDR_WIDTH   ),
        .numwords_b            (2**ADDR_WIDTH   ),
        .operation_mode        ("DUAL_PORT"     ),
        .outdata_aclr_b        ("NONE"          ),
        .outdata_sclr_b        ("NONE"          ),
        .outdata_reg_b         (OUTDATA_REG_B   ),
        .power_up_uninitialized("FALSE"         ),
        .ram_block_type        (MEM_STYLE       ),
        .widthad_a             (ADDR_WIDTH      ),
        .widthad_b             (ADDR_WIDTH      ),
        .width_a               (FULL_DATA_WIDTH ),
        .width_b               (FULL_DATA_WIDTH ),
        .width_byteena_a       (WIDTH_BYTEENA_A ) 
    )
    u_altera_syncram
    (
        .address_a      (I_wr_addr ),
        .address_b      (I_rd_addr ),
        .byteena_a      (byteena_a ),
        .clock0         (I_wr_clk  ),
        .clock1         (I_rd_clk  ),
        .data_a         (I_wr_data ),
        .wren_a         (1'b1      ),
        .q_b            (O_rd_data ),
        .aclr0          (1'b0      ),
        .aclr1          (1'b0      ),
        .address2_a     (1'b1      ),
        .address2_b     (1'b1      ),
        .addressstall_a (1'b0      ),
        .addressstall_b (1'b0      ),
        .byteena_b      (1'b1      ),
        .clocken0       (1'b1      ),
        .clocken1       (1'b1      ),
        .clocken2       (1'b1      ),
        .clocken3       (1'b1      ),
        .data_b         (data_b    ),
        .eccencbypass   (1'b0      ), 
        .eccencparity   (8'b0      ), 
        .eccstatus      (          ), 
        .q_a            (          ), 
        .rden_a         (1'b0      ), 
        .rden_b         (rd_en     ),
        .sclr           (1'b0      ), 
        .wren_b         (1'b0      )  
    );
    
endmodule
