// HongXin Copyright 2010~2019
// HongXin Company Confidential
// Company : HongXin Telecom .Inc
// Copyright(c) 2019, HongXin Telecom .Inc, All right reserved

//---------------------------------------------------------------------
// AUTHOR          : Tang Dongsheng
//---------------------------------------------------------------------
// Tool version    : ISE14.7 / Vivado 2018 / Quartus 20.1
//---------------------------------------------------------------------
// Release History :
//---------------------------------------------------------------------
// Version    |    Date      | Description
//---------------------------------------------------------------------
// 1.0-0      |  2015-05-15  | first edit
// 1.1-0      |  2018-08-01  | support different read and write data width
// 1.2-0      |  2020-07-21  | support altera M20K/M9K byte write mode
//---------------------------------------------------------------------
// Main Function   :
// 1. 用代码实现一个简单双口RAM
// 2. 支持实现RAM方式的可参数化，支持Altera和Xilinx环境
// 3. RAM的数据宽度和地址宽度可参数化
//---------------------------------------------------------------------
`timescale 1ns / 1ps

module ram_sdp_base_common #
(//sdp : Simple Dual Port
    parameter ADDR_WIDTH        =      9,
    parameter DATA_WIDTH        =     18,
    parameter REG_OUT           =      1,//0<=REG_OUT<=2. It's highly recommended to set this parama bigger than '0'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
    parameter MEM_STYLE         = "AUTO",//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
    parameter USE_RD_EN         =      0,//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
    parameter COL_NUM           =      1,//Number of byte write enable bit
    
    //auto generated by the parama above, no need to allocate
    parameter FULL_DATA_WIDTH  = DATA_WIDTH*COL_NUM
)
(
    input                        I_wr_clk ,
    input  [COL_NUM-1:0]         I_wr_en  ,
    input  [ADDR_WIDTH-1:0]      I_wr_addr,
    input  [FULL_DATA_WIDTH-1:0] I_wr_data,
    input                        I_rd_clk ,
    input                        I_rd_en  ,
    input  [ADDR_WIDTH-1:0]      I_rd_addr,
    output [FULL_DATA_WIDTH-1:0] O_rd_data
);
    
    (* RAM_STYLE=MEM_STYLE *)
    (* ramstyle=MEM_STYLE *)
    reg [FULL_DATA_WIDTH-1:0] data [(2**ADDR_WIDTH)-1:0];
    
    genvar i;
    generate
        for(i=0;i<COL_NUM;i=i+1)
        begin : byte_write
            
            always @ (posedge I_wr_clk)
            begin
                if(I_wr_en[i])
                    data[I_wr_addr][(i+1)*DATA_WIDTH-1:i*DATA_WIDTH] <= I_wr_data[(i+1)*DATA_WIDTH-1:i*DATA_WIDTH];
            end
            
        end
    
    
    if(REG_OUT==0)
        begin : REG_OUT0
            assign O_rd_data = data[I_rd_addr];
        end
    else if(REG_OUT==1)
        begin : REG_OUT1
            
            reg [FULL_DATA_WIDTH-1:0] data_o1;
            always @ (posedge I_rd_clk)
            begin
                if(!USE_RD_EN)
                    data_o1 <= data[I_rd_addr];
                else if(I_rd_en)
                    data_o1 <= data[I_rd_addr];
            end
            assign O_rd_data = data_o1;
             
        end
    else if(REG_OUT==2)
        begin: REG_OUT2
            
            reg [FULL_DATA_WIDTH-1:0] data_o1;
            reg [FULL_DATA_WIDTH-1:0] data_o2;
            reg                  rden_o1;
            always @ (posedge I_rd_clk)
            begin
                data_o1  <= data[I_rd_addr];
                rden_o1  <= I_rd_en;
                if(!USE_RD_EN)
                    data_o2 <= data_o1;
                else if(rden_o1)
                    data_o2 <= data_o1;
            end
            assign O_rd_data = data_o2;
            
        end
    else
        begin : NO_SUPPORT
            assign O_rd_data = 1'b0;
        end
    
    endgenerate
endmodule
