// HongXin Copyright 2010~2019
// HongXin Company Confidential
// Company : HongXin Telecom .Inc
// Copyright(c) 2019, HongXin Telecom .Inc, All right reserved

//---------------------------------------------------------------------
// AUTHOR          : Tang Dongsheng
//---------------------------------------------------------------------
// Tool version    : ISE14.7 / Vivado 2015
//---------------------------------------------------------------------
// Release History :
//---------------------------------------------------------------------
// Version    |    Date      | Description
//---------------------------------------------------------------------
// 1.0-0      |  2015-05-15  | first edit
// 1.1-0      |  2018-08-01  | support different read and write data width
// 1.2-0      |  2019-07-31  | a. add byte write enable feature
//                             b. use 'M2' model to reduce ram usage
//                             c. improve timing when REG_OUT = 2 
//---------------------------------------------------------------------
// Main Function   :
// 1. 用代码实现一个简单双口RAM
// 2. 支持实现RAM方式的可参数化，支持Altera和Xilinx环境
// 3. RAM的数据宽度和地址宽度可参数化
// 4. 支持不同的读写数据位宽
//---------------------------------------------------------------------
`timescale 1ns / 1ps

module ram_sdp #
(//sdp : Simple Dual Port
    parameter ADDR_WIDTH        =      9,
    parameter DATA_WIDTH        =     18,
    parameter REG_OUT           =      1,//It's highly recommended to set this parama bigger than '0'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
    parameter MEM_STYLE         = "AUTO",//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
    parameter USE_RD_EN         =      0,//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
    parameter DIFF_ADDR_WIDTH   =      0,//Negetive value means the read data width is 2^N base than write data. Posetive value means the write data width is 2^N base than read data.
    
    //auto generated by the parama above, no need to allocate
    parameter N             = (DIFF_ADDR_WIDTH>0) ? DIFF_ADDR_WIDTH : -DIFF_ADDR_WIDTH,
    parameter RD_ADDR_WIDTH = ADDR_WIDTH+DIFF_ADDR_WIDTH,
    parameter RD_DATA_WIDTH = (DIFF_ADDR_WIDTH>0) ? DATA_WIDTH/(2**N) : DATA_WIDTH*(2**N)
)
(
    input                      I_wr_clk ,
    input                      I_wr_en  ,
    input  [ADDR_WIDTH-1:0]    I_wr_addr,
    input  [DATA_WIDTH-1:0]    I_wr_data,
    input                      I_rd_clk ,
    input                      I_rd_en  ,
    input  [RD_ADDR_WIDTH-1:0] I_rd_addr,
    output [RD_DATA_WIDTH-1:0] O_rd_data
);
    
    localparam EDIAN = 1;//Set this parama to 1, to keep the same EDIAN result with Xilinx IP
    //////////////////////////////////////////////////////////////////////////////////////////////////////////
    //                                                  //                                                  //
    //  +----------+                                    //  +----------+                                    //
    //  |          |   _   _   _   _   _   _   _   _    //  |          |          _______         _______   //
    //  |  CLK_IN  | _| |_| |_| |_| |_| |_| |_| |_| |_  //  |  CLK_IN  | ________|       |_______|       |  //
    //  |          |                                    //  |          |                                    //
    //  +----------+ +---+---+---+---+---+---+---+---+  //  +----------+ +---------------+---------------+  //
    //  |   DIN    | |D0 |D1 |D2 |D3 |D4 |D5 |D6 |D7 |  //  |   DIN    | |    D0D1D2D3   |    D4D5D6D7   |  //
    //  +----------+ +---+---+---+---+---+---+---+---+  //  +----------+ +---------------+---------------+  //
    //  |          |          _______         _______   //  |          |   _   _   _   _   _   _   _   _    //
    //  |  CLK_OUT | ________|       |_______|       |  //  | CLK_OUT  | _| |_| |_| |_| |_| |_| |_| |_| |_  //
    //  |          |                                    //  |          |                                    //
    //  +------+---+ +---------------+---------------+  //  +------+---+ +---+---+---+---+---+---+---+---+  //
    //  | DOUT | 1 | |    D0D1D2D3   |    D4D5D6D7   |  //  | DOUT | 1 | |D0 |D1 |D2 |D3 |D4 |D5 |D6 |D7 |  //
    //  |      +---+ +---------------+---------------+  //  |      +---+ +---+---+---+---+---+---+---+---+  //
    //  |EDIAN | 0 | |    D3D2D1D0   |    D7D6D5D4   |  //  |EDIAN | 0 | |D3 |D2 |D1 |D0 |D7 |D6 |D5 |D4 |  //
    //  +------+---+ +---------------+---------------+  //  +------+---+ +---+---+---+---+---+---+---+---+  //
    //                                                  //                                                  //
    //////////////////////////////////////////////////////////////////////////////////////////////////////////

    genvar i,k;
    generate 
    if(DIFF_ADDR_WIDTH>0)
        begin : wrN_rd1
            
            //Write x bit data to RAM at one write cycle, and only output x/2**N bit data at one read cycle.
            //Two models are used to implement this RAM.
            //
            //M1.  Use small width RAMs to form big width RAM. Small RAM have bit width of x/2**N, and big RAM
            //     have bit width of x. We write the small RAM together and read them seperatly.
            //
            //M2.  Use a big width RAM directly. When we read the RAM, read data with multi-address will come out 
            //     together. Then, we use a MUX to select the output data.
            //
            //M1 model have better power consumtion perfance when we use the read enable function of Block RAM. 
            //M2 model can save Block RAM in some situation.
            //Forgive me that I can't support these two features both, I will use M2 model here.
            //
            //For example (Xilinx)
            //  +----------+----------+----------+----------+-----------+-----------+
            //  | WR Width | WR Depth | RD Width | RD Depth |  M1.RAM   |  M2.RAM   |
            //  +----------+----------+----------+----------+-----------+-----------+
            //  |   4*36   |   512    |   4*9    |   2048   |  4 * M18K |  4 * M18K |
            //  +----------+----------+----------+----------+-----------+-----------+
            //  |    36    |   512    |     9    |   2048   |  1 * M18K |  1 * M18K |
            //  +----------+----------+----------+----------+-----------+-----------+
            //  |    8     |   2048   |     2    |   8192   |  4 * M18K |  1 * M18K |
            //  +----------+----------+----------+----------+-----------+-----------+
            
            localparam REG_OUT_S = (REG_OUT>2) ? 2 : ((REG_OUT>0) ?  1 : 0);
            // +-------------+--------------+
            // |   REG_OUT   |    REG_OUT_S |
            // +-------------+--------------+
            // |     0       |       0      |
            // +-------------+--------------+
            // |     1       |       1      |
            // +-------------+--------------+
            // |     2       |       1      |
            // +-------------+--------------+
            // |     >2      |       2      |
            // +-------------+--------------+
            
            wire [DATA_WIDTH-1:0]    rd_data             ;
            wire [RD_DATA_WIDTH-1:0] rd_data_i [2**N-1:0];
            for(i=0;i<2**N;i=i+1)
            begin : n //devide ram output data into 2**N group
                if(EDIAN==0)
                    assign rd_data_i[i]        = rd_data[(i+1)*RD_DATA_WIDTH-1:i*RD_DATA_WIDTH];
                else
                    assign rd_data_i[2**N-i-1] = rd_data[(i+1)*RD_DATA_WIDTH-1:i*RD_DATA_WIDTH];
            end
            
            ram_sdp_base #
            (
                .ADDR_WIDTH(ADDR_WIDTH),
                .DATA_WIDTH(DATA_WIDTH),
                .REG_OUT   (REG_OUT_S ),//0<=REG_OUT<=2. It's highly recommended to set this parama bigger than '0'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
                .MEM_STYLE (MEM_STYLE ),//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
                .USE_RD_EN (USE_RD_EN ),//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
                .COL_NUM   (1         ) //Number of byte write enable bit
            )
            u_ram_sdp_base
            (
                .I_wr_clk (I_wr_clk                   ),
                .I_wr_en  (I_wr_en                    ),
                .I_wr_addr(I_wr_addr                  ),
                .I_wr_data(I_wr_data                  ),
                .I_rd_clk (I_rd_clk                   ),
                .I_rd_en  (I_rd_en                    ),
                .I_rd_addr(I_rd_addr[ADDR_WIDTH+N-1:N]),
                .O_rd_data(rd_data                    )
            );   
            
            //read address sync, if needed
            reg [N-1:0] rd_addr_dly [1:0];
            always @ (posedge I_rd_clk)
            begin
                rd_addr_dly[0] <= I_rd_addr[N-1:0];
                rd_addr_dly[1] <= rd_addr_dly[0];
            end
            
            if(REG_OUT==0)//very poor timing result but 0 cycle reading delay, this ram can only be supported by logic resource.
                assign O_rd_data = rd_data_i[I_rd_addr[N-1:0]];
            else if(REG_OUT==1)//ram output data come to a MUX and then to user. If implemented by logic cell, have better performance than block ram.
                assign O_rd_data = rd_data_i[rd_addr_dly[0]];//Otherwise, this timing result is not so perfect.
            else//The most fast timing result model. Gernally, REG_OUT = 2 is enought.
                begin//REG_OUT > 2 will get the best timing result.
                    
                    //read data sync and mux, if needed
                    //we can put this mux before a Filp-Flop to improve timing.
                    reg [RD_DATA_WIDTH-1:0] rd_data_i_dly [REG_OUT-2:0];
                    
                    always @ (posedge I_rd_clk)
                    begin
                        rd_data_i_dly[0] <= rd_data_i[rd_addr_dly[REG_OUT_S-1]];
                    end
                    
                    for(k=1;k<REG_OUT-2;k=k+1)
                    begin : n
                        always @ (posedge I_rd_clk)
                        begin
                            rd_data_i_dly[k] <= rd_data_i_dly[k-1];
                        end
                    end
                    
                    assign O_rd_data = rd_data_i_dly[REG_OUT-2];
                    
                end
        end
    else
        begin : wr1_rdN
            
            //Write x bit data to RAM at one write cycle, and output x*(2**N) bit data at one read cycle.
            //Two models are used to implement this RAM.
            //
            //M1.  Use small width RAMs to form big width RAM. Small RAM have bit width of x, and big RAM
            //     have bit width of x*(2**N). We write the small RAM seperatly and read them together.
            //
            //M2.  Use a big width RAM directly, and use the byte write features of Block RAM.
            //
            //We use M2 model here, because M2 model may save Block RAM in some situation. 
            //
            //For example (Xilinx)
            //  +----------+----------+----------+----------+-----------+-----------+
            //  | WR Width | WR Depth | RD Width | RD Depth |  M1.RAM   |  M2.RAM   |
            //  +----------+----------+----------+----------+-----------+-----------+
            //  |     9    |  2048    |    36    |   512    |  4 * M18K |  1 * M18K |
            //  +----------+----------+----------+----------+-----------+-----------+
            //  |    36    |  2048    |   4*36   |   512    |  4 * M18K |  4 * M18K |
            //  +----------+----------+----------+----------+-----------+-----------+
            
            wire [2**N-1:0]              wr_en  ;
            wire [DATA_WIDTH*(2**N)-1:0] wr_data;
            
            if(N>0)
                for(i=0;i<2**N;i=i+1)
                begin : n
                    if(EDIAN==0)
                        assign wr_en[i]        = I_wr_en&&(I_wr_addr[N-1:0]==i);
                    else
                        assign wr_en[2**N-i-1] = I_wr_en&&(I_wr_addr[N-1:0]==i);
                end
            else//N==0
                assign wr_en[0] = I_wr_en;
            
            assign wr_data = {2**N{I_wr_data}};
            
            localparam REG_OUT_S = (REG_OUT>2) ? 2 : REG_OUT;
            // +-------------+--------------+
            // |   REG_OUT   |    REG_OUT_S |
            // +-------------+--------------+
            // |     0       |       0      |
            // +-------------+--------------+
            // |     1       |       1      |
            // +-------------+--------------+
            // |     2       |       2      |
            // +-------------+--------------+
            // |     >2      |       2      |
            // +-------------+--------------+
            
            
            wire [RD_DATA_WIDTH-1:0] rd_data_i;
            
            ram_sdp_base #
            (
                .ADDR_WIDTH(ADDR_WIDTH-N),
                .DATA_WIDTH(DATA_WIDTH  ),
                .REG_OUT   (REG_OUT_S   ),//It's highly recommended to set this parama to '1'or '2'. Otherwise, synthieser will use logic resource to build the RAM unless the value of MEM_STYLE.
                .MEM_STYLE (MEM_STYLE   ),//For Xilinx : use "AUTO", "BLOCK", or "DISTRIBUTED" ; For Altera : use "logic", "M512", "M4K", "M9K", "M20K", "M144K", "MLAB", or "M-RAM".
                .USE_RD_EN (USE_RD_EN   ),//If USE_RD_EN = 1, user should drive I_rd_en port as read enable. Otherwise, this port is unused, left it un-conected or assign it with any value.
                .COL_NUM   (2**N        ) //Number of byte write enable bit
            )
            u_ram_sdp_base
            (
                .I_wr_clk (I_wr_clk                 ),
                .I_wr_en  (wr_en                    ),
                .I_wr_addr(I_wr_addr[ADDR_WIDTH-1:N]),
                .I_wr_data(wr_data                  ),
                .I_rd_clk (I_rd_clk                 ),
                .I_rd_en  (I_rd_en                  ),
                .I_rd_addr(I_rd_addr                ),
                .O_rd_data(rd_data_i                )
            );
            
            if(REG_OUT>2)
                begin
                    
                    reg [RD_DATA_WIDTH-1:0] rd_data_i_dly [REG_OUT-3:0];
                    
                    always @ (posedge I_rd_clk)
                    begin
                        rd_data_i_dly[0] <= rd_data_i;
                    end
                    
                    for(k=1;k<REG_OUT-3;k=k+1)
                    begin: n
                        always @ (posedge I_rd_clk)
                        begin
                            rd_data_i_dly[k] <= rd_data_i_dly[k-1];
                        end
                    end
                    
                    assign O_rd_data = rd_data_i_dly[REG_OUT-3];
                    
                end
            else
                begin
                    
                    assign O_rd_data = rd_data_i;
                    
                end
            
        end
    endgenerate
    
endmodule
